### ISSUE TITLE
Why can't we use texlive yum packages?

### ISSUE THREAD

**Issue by mpharrigan** [omnia-md/linux-anvil-openmm#1]
Are they too old? Were they too old for centos 5 but possibly new enough now?

**Comment by jchodera** [comment]
Could give it a try! Can't recall if I tried this myself with CentOS 6.

**Comment by Lnaden** [comment]
We can't use the yum texlive packages since `tlmgr` is not installed, so if we need new packages, we can't really get them :(

**Comment by mpharrigan** [comment]
Yeah to follow up on this: I thought it would be like ubuntu where you could get all the packages from the system package manager without tlmgr, but it turns out centos barely has latex at all. so yeah... tlmgr it is

**Comment by Lnaden** [comment]
Not a problem. I just figured I would close the issue now since I was dealing with exactly this problem with the most recent updates. The annoying part is that its not really documented that it *doesn't* provide `tlmgr`
