### ISSUE TITLE
Create a CUDA 9.1 build

### ISSUE THREAD

**Issue by Lnaden** [omnia-md/linux-anvil-openmm#7]
Issue to track the build of a AMD3.0 + TexLive 2017 + CUDA 9.1 build

I am working on building this.

@peastman I am looking at the CUDA installers [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=RHEL&target_version=6&target_type=rpmlocal) and there are three patches for this version of CUDA, does the docker image need these patches installed for OpenMM to build correctly against, or is un-patched the base version fine?

Specific details of the patches:
1. cuBLAS Patch Update: This update to CUDA 9.1 includes new GEMM kernels optimized for the Volta architecture and improved heuristics to select GEMM kernels for given input sizes.
1. CUDA Compiler Patch Update: This update to CUDA 9.1 includes a bug fix to the PTX assembler (ptxas). The fix resolves an issue when compiling code that performs address calculations using large immediate operands.
1. cuBLAS Patch: This CUDA 9.1 patch includes fixes to GEMM optimizations for convolutional sequence to sequence (seq2seq) models.

**Comment by peastman** [comment]
It sounds like those are just bug fixes, so probably the base version is fine.  As long as they don't change the SONAME of any libraries they should be compatible.

**Comment by Lnaden** [comment]
Great! That does not sound like something a cuda patch would do, so I don't think they do since they are not introducing new libraries

**Comment by Lnaden** [comment]
This has been created in the `texlive-amd30-cuda91` branch.
